USE [master]
GO

/****** Object:  Database [CompensationBenefitsDB]    Script Date: 05-10-2026 11.20.37 AM ******/
CREATE DATABASE [CompensationBenefitsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CompensationBenefitsDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\CompensationBenefitsDB.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CompensationBenefitsDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\CompensationBenefitsDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CompensationBenefitsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CompensationBenefitsDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CompensationBenefitsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CompensationBenefitsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CompensationBenefitsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CompensationBenefitsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET RECOVERY FULL 
GO

ALTER DATABASE [CompensationBenefitsDB] SET  MULTI_USER 
GO

ALTER DATABASE [CompensationBenefitsDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CompensationBenefitsDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CompensationBenefitsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CompensationBenefitsDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CompensationBenefitsDB] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [CompensationBenefitsDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CompensationBenefitsDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [CompensationBenefitsDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CompensationBenefitsDB] SET  READ_WRITE 
GO

